name: learning_pose_detection_example
description: Demonstrates how to use the learning_pose_detection plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.1
  learning_pose_detection: 
    path: ../
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.0
  shared_preferences: ^2.1.0
  camera: ^0.9.4+5
  tflite: ^1.1.2
  animated_text_kit: ^4.2.2
  intl: ^0.18.1
  learning_input_image: ^0.0.6+2
  image_picker: ^0.8.7+1
  image: ^3.1.3
  pdf: ^3.8.4
  path_provider: ^2.0.15
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_gauges: ^22.2.10
  image_cropper: ^4.0.1
  http: ^0.13.6
  video_player: ^2.8.3
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/images/
    - assets/mcq_images/
    - assets/videos/
