import 'package:learning_pose_detection_example/models/task_management.dart';


List<TaskManagementQuestion> sampleTasks = [
  TaskManagementQuestion(
    id: 1,
    title: 'Activities at Home',
    question: 'How should you organize your time?',
    category: 'Homestead',
    points: 6,
    tasks: [
      'Make bed in the morning',
      'Help set the dinner table at night',
      'Put away toys before going to school',
      'Play piano for 15 minutes in evening',
      'Pick up clothes and put them in the hamper before going to sleep'
    ],
    answer: ['Pick up clothes and put them in the hamper before going to sleep',
      'Help set the dinner table at night',
      'Play piano for 15 minutes in evening',
      'Put away toys before going to school',
      'Make bed in the morning'
    ],
    difficultyLevel: 1,
  ),
  TaskManagementQuestion(
    id: 2,
    title: 'Sort Your Toys',
    question: 'How should you organize your toys?',
    category: 'Homestead',
    points: 6,
    tasks: [
      'Make bed in the morning',
      'Help set the dinner table at night',
      'Put away toys before going to school',
      'Play piano for 15 minutes in evening',
      'Pick up clothes and put them in the hamper before going to sleep'
    ],
    answer: ['Pick up clothes and put them in the hamper before going to sleep',
      'Help set the dinner table at night',
      'Play piano for 15 minutes in evening',
      'Put away toys before going to school',
      'Make bed in the morning'
    ],
    difficultyLevel: 1,
  ),
  TaskManagementQuestion(
    id: 3,
    title: 'School Activities',
    question: 'What tasks do you need to complete for school?',
    category: 'School',
    points: 1,
    tasks: [
      'Finish In-Class Worksheet due on tomorrow',
      'Pack backpack for tomorrow',
      'Study for upcoming test in a week',
      'Do 5 math problems and read 2 chapters of the book',
      'Sharpen 3 pencils for the next class'
    ],
    answer: [
      'Study for upcoming test in a week',
      'Finish In-Class Worksheet due on tomorrow',
      'Do 5 math problems and read 2 chapters of the book',
      'Pack backpack for tomorrow',
      'Sharpen 3 pencils for the next class'
    ],
    difficultyLevel: 2,
  ),
  TaskManagementQuestion(
    id: 4,
    title: 'Other Activities',
    question: 'What other activities do you have to do?',
    category: 'Other Activities',
    points: 1,
    tasks: [
      'Play tag for 30 minutes',
      'Attend friend\'s birthday party in the evening at 4 pm',
      'Doctor\'s appointment in the evening at 3 pm',
      'Use the watering can to sprinkle water on the houseplants',
      'Rake leaves for 15 minutes'
    ],
    answer: [
      'Attend friend\'s birthday party in the evening at 4 pm',
      'Doctor\'s appointment in the evening at 3 pm',
      'Play tag for 30 minutes',
      'Rake leaves for 15 minutes',
      'Use the watering can to sprinkle water on the houseplants'
    ],
    difficultyLevel: 3,
  ),
  // TaskManagementQuestion(
  //   id: 1,
  //   title: 'Make Your Bed',
  //   question: 'What is the first thing you do after waking up?',
  //   category: 'Homestead',
  //   points: 5,
  //   tasks: [
  //     'Arrange the pillows',
  //     'Smooth out the bedsheet',
  //     'Fold the blanket neatly',
  //   ],
  //   answer: [
  //     'Fold the blanket neatly',
  //     'Arrange the pillows',
  //     'Smooth out the bedsheet',
  //   ],
  //   difficultyLevel: 1,
  // ),
  // TaskManagementQuestion(
  //   id: 2,
  //   title: 'Clean Your Room',
  //   question: 'What is the best way to organize your toys?',
  //   category: 'Homestead',
  //   points: 10,
  //   tasks: [
  //     'Leave them on the floor',
  //     'Stack them in a pile',
  //     'Sort them into bins',
  //   ],
  //   answer: ['Sort them into bins'],
  //   difficultyLevel: 2,
  // ),
  // TaskManagementQuestion(
  //   id: 3,
  //   title: 'Set the Table',
  //   question: 'What do you need to set on the dining table?',
  //   category: 'Homestead',
  //   points: 7,
  //   tasks: [
  //     'Nothing',
  //     'Books and toys',
  //     'Plates, forks, and knives',
  //   ],
  //   answer: ['Plates, forks, and knives'],
  //   difficultyLevel: 1,
  // ),
  // TaskManagementQuestion(
  //   id: 4,
  //   title: 'Water the Plants',
  //   question: 'What do plants need to grow healthy?',
  //   category: 'Garden',
  //   points: 8,
  //   tasks: [
  //     'Sunlight',
  //     'Fertilizer',
  //     'Water',
  //   ],
  //   answer: ['Water'],
  //   difficultyLevel: 2,
  // ),
  // TaskManagementQuestion(
  //   id: 5,
  //   title: 'Feed the Pet',
  //   question: 'What should you give to your pet for food?',
  //   category: 'Homestead',
  //   points: 6,
  //   tasks: [
  //     'Water',
  //     'Chocolate',
  //     'Vegetables',
  //   ],
  //   answer: ['Water', 'Chocolate', 'Vegetables'],
  //   difficultyLevel: 1,
  // ),
  // TaskManagementQuestion(
  //   id: 6,
  //   title: 'Brush Your Teeth',
  //   question: 'What is the first step to brushing your teeth?',
  //   category: 'Personal',
  //   points: 4,
  //   tasks: [
  //     'Apply toothpaste on the toothbrush',
  //     'Start brushing',
  //     'Rinse your mouth',
  //   ],
  //   answer: ['Apply toothpaste on the toothbrush', 'Start brushing', 'Rinse your mouth'],
  //   difficultyLevel: 1,
  // ),
  // TaskManagementQuestion(
  //   id: 7,
  //   title: 'Sort Laundry',
  //   question: 'How should you sort your laundry?',
  //   category: 'Homestead',
  //   points: 9,
  //   tasks: [
  //     'Separate by color',
  //     'Mix everything together',
  //     'Fold them as is',
  //   ],
  //   answer: ['Separate by color', 'Mix everything together', 'Fold them as is'],
  //   difficultyLevel: 2,
  // ),
  // TaskManagementQuestion(
  //   id: 8,
  //   title: 'Take Out the Trash',
  //   question: 'What should you do with the trash when it\'s full?',
  //   category: 'Homestead',
  //   points: 7,
  //   tasks: [
  //     'Take it out to the bin',
  //     'Leave it in the room',
  //     'Ignore it',
  //   ],
  //   answer: ['Take it out to the bin', 'Leave it in the room', 'Ignore it'],
  //   difficultyLevel: 2,
  // ),
  // TaskManagementQuestion(
  //   id: 9,
  //   title: 'Prepare Breakfast',
  //   question: 'What do you need to prepare a simple breakfast?',
  //   category: 'Homestead',
  //   points: 8,
  //   tasks: [
  //     'Bread and butter',
  //     'Cereal and milk',
  //     'No breakfast needed',
  //   ],
  //   answer: ['Bread and butter', 'Cereal and milk', 'No breakfast needed'],
  //   difficultyLevel: 1,
  // ),
  // TaskManagementQuestion(
  //   id: 10,
  //   title: 'Tidy Up Your Desk',
  //   question: 'What should you do to keep your desk organized?',
  //   category: 'Personal',
  //   points: 6,
  //   tasks: [
  //     'Clear unnecessary items',
  //     'Pile everything up',
  //     'Leave it messy',
  //   ],
  //   answer: ['Clear unnecessary items'],
  //   difficultyLevel: 1,
  // ),
  // TaskManagementQuestion(
  //   id: 11,
  //   title: 'Water the Garden',
  //   question: 'What do plants need to grow healthy in the garden?',
  //   category: 'Garden',
  //   points: 8,
  //   tasks: [
  //     'Water',
  //     'Fertilizer',
  //     'Sunlight',
  //   ],
  //   answer: ['Water', 'Fertilizer', 'Sunlight'],
  //   difficultyLevel: 2,
  // ),
  // TaskManagementQuestion(
  //   id: 12,
  //   title: 'Fold Your Clothes',
  //   question: 'What should you do after your clothes are washed?',
  //   category: 'Homestead',
  //   points: 7,
  //   tasks: [
  //     'Fold them neatly',
  //     'Leave them in a pile',
  //     'Hang them wet',
  //   ],
  //   answer: ['Fold them neatly'],
  //   difficultyLevel: 1,
  // ),
  // TaskManagementQuestion(
  //   id: 13,
  //   title: 'Pack Your Bag',
  //   question: 'What should you pack in your school bag?',
  //   category: 'Homestead',
  //   points: 9,
  //   tasks: [
  //     'Books and notebooks',
  //     'Toys and games',
  //     'Nothing',
  //   ],
  //   answer: ['Books and notebooks'],
  //   difficultyLevel: 2,
  // ),
  // TaskManagementQuestion(
  //   id: 14,
  //   title: 'Help with Cooking',
  //   question: 'What can you do to help with cooking in the kitchen?',
  //   category: 'Homestead',
  //   points: 8,
  //   tasks: [
  //     'Chop vegetables',
  //     'Play outside',
  //     'Watch TV',
  //   ],
  //   answer: ['Chop vegetables'],
  //   difficultyLevel: 2,
  // ),
  // TaskManagementQuestion(
  //   id: 15,
  //   title: 'Sort Your Toys',
  //   question: 'How should you organize your toys?',
  //   category: 'Homestead',
  //   points: 6,
  //   tasks: [
  //     'Put them in bins',
  //     'Scatter them around',
  //     'Leave them on the floor',
  //   ],
  //   answer: ['Put them in bins'],
  //   difficultyLevel: 1,
  // ),

];
